version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: deps(gh)
  assignees:
  - hayatek-jp
  open-pull-requests-limit: 10
  target-branch: main

- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: deps
    prefix-development: deps(dev)
  assignees:
  - hayatek-jp
  open-pull-requests-limit: 30
  target-branch: main
